### ISSUE TITLE
how to download original files?

### ISSUE THREAD

**Issue by kxxc** [k4rtik/popclip-ytdl#2]
I LOVE this Extension,
But how to download original files?

Why the file was smaller than flies download directly by terminal?

thank you!

**Comment by k4rtik** [comment]
How are you downloading directly on the terminal?

**Comment by kxxc** [comment]
> How are you downloading directly on the terminal?

wow thanks for your reply, 

youtube-dl https://youtube url

I just now find another extension and add action to paste the "youtube-dl https://youtube url" to terminal and download.

**Comment by k4rtik** [comment]
Can you test again? I just made a change: https://github.com/k4rtik/popclip-ytdl/commit/d2dbc802d3ac67cd6ed1f995176b11f764981d25

**Comment by kxxc** [comment]
> Can you test again? I just made a change: [d2dbc80](https://github.com/k4rtik/popclip-ytdl/commit/d2dbc802d3ac67cd6ed1f995176b11f764981d25)

WOW! it works! thank you for your passion and updated after 4 years ago! 😂

**Comment by k4rtik** [comment]
Thanks, I did not know if anyone used this extension at all. Even I was not using it for many years.

So really users like you help these small projects keep going. Thanks for filing this issue and sharing your enthusiasm. 😂
